site_name: UniEnv
site_description: Unified robot environment framework documentation
site_url: https://unienvorg.github.io/UniEnv/
repo_url: https://github.com/UniEnvOrg/UniEnv
repo_name: UniEnvOrg/UniEnv

theme:
  name: material
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            filters:
              - "!^_"
            heading_level: 2
            inherited_members: true
            members_order: source
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: true
            show_root_full_path: false
            show_root_heading: false
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
